# Generated by Django 4.2 on 2023-05-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
